# Generated by Django 3.0.7 on 2020-06-28 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='artwork',
            field=models.ImageField(default=None, upload_to='artwork/'),
            preserve_default=False,
        ),
    ]
