# Generated by Django 3.0.7 on 2020-06-28 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0002_album_artwork'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='artwork',
        ),
    ]
