# Generated by Django 3.0.7 on 2020-06-28 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0003_remove_album_artwork'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='year',
            field=models.IntegerField(default=2010),
            preserve_default=False,
        ),
    ]
