# Generated by Django 3.0.7 on 2020-06-29 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0005_auto_20200628_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='artworkURL',
            field=models.URLField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
