# Generated by Django 3.0.7 on 2020-06-29 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0006_album_artworkurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='artworkURL',
            field=models.URLField(max_length=255, null=True),
        ),
    ]
