# Generated by Django 3.0.7 on 2020-06-29 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0008_auto_20200629_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='artworkURL',
            field=models.URLField(default='https://e.snmc.io/i/600/w/5e3cd354d253c7dc67561f977b78933a/6862767', max_length=255),
        ),
    ]
