# Generated by Django 3.0.7 on 2020-06-29 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0009_auto_20200629_1150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='artworkURL',
        ),
    ]
