# Generated by Django 3.0.7 on 2020-06-29 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0010_remove_album_artworkurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='artworkURL',
            field=models.URLField(default='https://via.placeholder.com/150', max_length=255),
        ),
    ]
