# Generated by Django 3.0.7 on 2020-06-29 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0012_auto_20200629_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='artworkURL',
            field=models.URLField(default='https://via.placeholder.com/150', max_length=255),
        ),
    ]
