# Generated by Django 3.0.7 on 2020-06-29 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0013_auto_20200629_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='artworkURL',
            field=models.URLField(max_length=255),
        ),
    ]
