# Generated by Django 3.0.7 on 2020-06-29 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0014_auto_20200629_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='colors',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
